# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c09424d37b29affe8c6e8f33538781d"
name = "point-exchange-v2"
application_url = "https://technical-details-controversy-decided.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/app/orders_fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders_create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,read_customers,read_discounts,read_fulfillments,read_metaobjects,read_orders,read_products,write_customers,write_discounts,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://technical-details-controversy-decided.trycloudflare.com/api/auth" ]

[app_proxy]
url = "/api"
prefix = "apps"
subpath = "points-exchange"